question_data = [
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "In the 1988 film &quot;Akira&quot;, Tetsuo ends up destroying Tokyo.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "Studio Ghibli is a Japanese animation studio responsible for the films &quot;Wolf Children&quot; and"
                 " &quot;The Boy and the Beast&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "In Kill La Kill, the weapon of the main protagonist is a katana. ", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "The anime &quot;Lucky Star&quot; follows the story of one girl who is unaware she is God.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "No Game No Life first aired in 2014.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": r"Gosho Aoyama Made This Series: (Detective Conan \/ Case Closed!)", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "The name of the attack &quot;Kamehameha&quot; in Dragon Ball Z was named after a famous king of"
                 " Hawaii.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "Kiznaiver is an adaptation of a manga.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "In the &quot;To Love-Ru&quot; series, Golden Darkness is sent to kill Lala Deviluke.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "In Chobits, Hideki found Chii in his apartment.", "correct_answer": "False",
     "incorrect_answers": ["True"]}]
